notifications:
  commits: site-pub@aries.apache.org
  issues: site-pub@aries.apache.org
  pullrequests: site-pub@aries.apache.org
  jira_options: link label link label

staging:
  profile: beta
  whoami: asf-site
